### ISSUE TITLE
ImgIOEXception CImg<unsigned char>::load<>:failed to recognition format of life

### ISSUE THREAD

**Issue by fangxu622** [AmazingZhen/ImageStitching#1]
![image](https://cloud.githubusercontent.com/assets/16681534/15206281/8f8704da-1850-11e6-905c-5eeaa803ce83.png)

 VS2013,Debug X64 environment~ when i run it ,occured this probelem

**Comment by fangxu622** [comment]
how to make CIMG support JPG ````

**Comment by AmazingZhen** [comment]
You must also have installed the **_ImageMagick_** package in order to be able to read JPG images.

For more details, please view this website: 
[http://www.imagemagick.org/script/install-source.php#windows](http://www.imagemagick.org/script/install-source.php#windows)

**Comment by fangxu622** [comment]
i'm a leaner on Programing and Algorithm~thank you ~the problem has been solved ~

**Comment by AmazingZhen** [comment]
We are all learners. :)

**Comment by alanMachineLeraning** [comment]
4	IntelliSense:  无法打开 源 文件 "vl/generic.h"	f:\朗科\工作资料\金钱猫\全景拼接\ImageStitching-master\ImageStitching\Match.h	19	1	ImageStitching
